name = "nxlink-sync-planetgroup-worker"
main = "cloudflare-worker-sync.ts"
compatibility_date = "2026-08-23"
account_id = "b771f88cc6e239524474b06e15637bf4"

# Cron trigger: run every 1 minute
[triggers]
crons = ["* * * * *"]

[vars]
SUPABASE_URL = "https://qcxcgdmrcijikkbufjkq.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjeGNnZG1yY2lqaWtrYnVmamtxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NzQ0NTAwOSwiZXhwIjoyMTAzMDIxMDA5fQ.Cnqx4zb-96tXsl-H2868FqNJBo_EglrY8CVZelNXf0Q"
NXLINK_WEBHOOK_URL = "https://hype-hr-441002907541.asia-southeast1.run.app/intake/chatbot"
NXLINK_WEBHOOK_CLIENT_ID = "hype-chatbot"
NXLINK_WEBHOOK_CLIENT_SECRET = "b7074fc1902d8ae2cd096612539700078f485611445c54d1d6bb06d226649443"
NXLINK_PLAT_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJ1SWQiOjU3OTk0LCJkZXZpY2VVbmlxdWVJZGVudGlmaWNhdGlvbiI6IjA0ODg1NTkwLWMwYzUtMTFmMS05MmFlLWQ1NzVmNjYwZjUyZiIsInV1SWQiOiI2YWMzYWQ1MGU0YjA3YTQ1OGU3ZjBhZjMifQ.d7mv3OgoFkfNDjIYu-7s8zkr9c-8uTRTMbFkeWGygC8"
